# This is a basic workflow to help you build docker
name: Docker Builds

# Controls when the action will run. 
on: [push]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # - name: Checkout to ZT repo
      #   uses: actions/checkout@master 
      #   with:
      #     repository: zulip/zulip-terminal
      #     token: ${{ github.token }}
        # run: |
        #   ssh-keygen
        #   ${{ github.token }}
        #   ssh-copy-id delton@remoteserver

      - name: docker build zulip-terminal
        run: |
          cd docker
          docker build -t zulip-terminal:latest -f Dockerfile.buster . --build-arg SOURCE=git
      - name: run zulip terminal
        run: |
          mkdir $HOME/.zulip
          docker run -v $HOME/.zulip:/.zulip zulip-terminal:latest
